### ISSUE TITLE
Geistiger Dünnpfiff zur Gruppenarbeit

### ISSUE THREAD

**Issue by Promichel** [Promichel/Rezeptkram#3]
Ralf wenn du Zeit hast kratz mal bitte iwas zusammen. Aber iwas einigermaßen positives ;) Wir werden es Projektmäßig auf jedenfall schaffen.
Wenn du sie schreibst, dann beton bitte auf jedenfall das wir in Ticketsystem und Projektmanagmentsystem verwendet haben. Das wir Repos verwendet haben, und das wir auch möglichkeiten hatten an allen Punkten zu kommentieren

**Comment by 11111000101** [comment]
https://docs.google.com/document/d/1nb7Ng2YSKno8tdlA3aKLtqDYezbVVl9nS8JiqAWN_4Y/edit?hl=de
